name: Publish PowerShell Module

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: houqp/download-release-assets@v1
        with:
          repo: Riot-Enterprises/RIOTPSTools
          match: "Release.zip"
          rename: Release.zip
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.POWERSHELL_GALLERY_KEY }}
        shell: pwsh
        run: |
          Expand-Archive -Path 'Release.zip' -Path release
          $Folder = Get-ChildItem Release -Directory | Select -First 1
          Publish-Module -Path $Folder -NuGetApiKey $env:NUGET_KEY -Verbose
