---
name: "tagged-release"

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        shell: pwsh
        run: |
          $command = Join-Path $env:GITHUB_WORKSPACE tools build.ps1
          $command += ' Install'
          write-output $command
          gci (Split-Path $command -Parent)
          iex $command
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            ${{ github.workspaces }}/*.zip
