name: Publish PowerShell Module

on:
  release:

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install from PSGallery
        shell: pwsh
        run: |
          write-output "This is a test"
